### PR TITLE
Fix critical dependency issue

### PR DESCRIPTION
**Pull request by bluelakee02**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X ] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I fixed app router on new next

**Which issue (if any) does this pull request address?**
#9 

[next-translate](https://github.com/aralroca/next-translate/issues/1029)

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
LGTM! Thanks for solving it by doing this transpilation.

**Comment by aralroca** [comment]
@bluelakee02 can you solve the failing tests? Probably you only need to update the snapshots! Thanks!

**Comment by bluelakee02** [comment]
@aralroca sure, I am on it, sorry about that :)

**Comment by bluelakee02** [comment]
@aralroca pushed

**Comment by aralroca** [comment]
@all-contributors please add @bluelakee02 for code

**Comment by aralroca** [comment]
@bluelakee02 I already did the release of the patch version, thanks for the contribution

**Pull request merged**
